In [5]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/weather_history.csv"
)

df.head()

,datetime,temperature,humidity,pressure,wind_speed,wind_direction,precipitation,cloud_cover,city
0,2025-09-16T00:00,9.4,93,1027.3,1.4,247,0.0,0,innopolis
1,2025-09-16T01:00,9.2,93,1027.2,0.8,297,0.0,0,innopolis
2,2025-09-16T02:00,9.0,93,1027.2,0.6,326,0.0,0,innopolis
3,2025-09-16T03:00,8.7,96,1027.0,0.7,346,0.0,0,innopolis
4,2025-09-16T04:00,7.3,100,1027.4,0.9,281,0.0,100,innopolis

In [8]:
df.shape

(43920, 9)

In [9]:
df["city"].unique()

<StringArray>
['innopolis', 'kazan', 'cheboksary', 'ulyanovsk', 'yoshkar_ola']
Length: 5, dtype: str

In [11]:
df.isna().sum()

datetime          0
temperature       0
humidity          0
pressure          0
wind_speed        0
wind_direction    0
precipitation     0
cloud_cover       0
city              0
dtype: int64

In [12]:
df["datetime"].head()

0    2025-09-16T00:00
1    2025-09-16T01:00
2    2025-09-16T02:00
3    2025-09-16T03:00
4    2025-09-16T04:00
Name: datetime, dtype: str

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\timyr\AppData\Roaming\Python\Python314\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\timyr\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\timyr\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\timyr\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\timyr\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/weather_history.csv",
    parse_dates=["datetime"]
)


print(df.head())

             datetime  temperature  humidity  pressure  wind_speed  \
0 2025-09-16 00:00:00          9.4        93    1027.3         1.4
1 2025-09-16 01:00:00          9.2        93    1027.2         0.8
2 2025-09-16 02:00:00          9.0        93    1027.2         0.6
3 2025-09-16 03:00:00          8.7        96    1027.0         0.7
4 2025-09-16 04:00:00          7.3       100    1027.4         0.9

   wind_direction  precipitation  cloud_cover       city
0             247            0.0            0  innopolis
1             297            0.0            0  innopolis
2             326            0.0            0  innopolis
3             346            0.0            0  innopolis
4             281            0.0          100  innopolis

In [9]:
df = pd.read_csv(
    "../data/processed//test.csv"
)

df.head()

,datetime,cheboksary_temperature,innopolis_temperature,kazan_temperature,ulyanovsk_temperature,yoshkar_ola_temperature,cheboksary_humidity,innopolis_humidity,kazan_humidity,ulyanovsk_humidity,...,yoshkar_ola_precipitation,cheboksary_cloud_cover,innopolis_cloud_cover,kazan_cloud_cover,ulyanovsk_cloud_cover,yoshkar_ola_cloud_cover,hour,day_of_week,month,target_temperature_3h
0,2026-07-05 16:00:00,25.5,28.0,30.0,29.7,27.0,71.0,50.0,42.0,42.0,...,0.0,67.0,69.0,85.0,79.0,67.0,16,6,7,25.6
1,2026-07-05 17:00:00,27.0,27.8,27.6,29.8,26.1,61.0,53.0,50.0,44.0,...,0.1,38.0,81.0,69.0,80.0,69.0,17,6,7,25.3
2,2026-07-05 18:00:00,26.3,25.7,26.7,28.9,26.4,67.0,62.0,57.0,50.0,...,0.2,29.0,88.0,85.0,94.0,54.0,18,6,7,24.3
3,2026-07-05 19:00:00,25.9,25.6,27.2,26.8,25.7,62.0,63.0,57.0,58.0,...,0.0,74.0,55.0,35.0,95.0,44.0,19,6,7,22.6
4,2026-07-05 20:00:00,24.6,25.3,26.7,26.1,25.0,61.0,65.0,59.0,57.0,...,0.0,88.0,77.0,88.0,73.0,77.0,20,6,7,21.0

KeyError: 'city'

In [6]:
df["target_temperature_3h"] = (
    df["innopolis_temperature"]
    .shift(-3)
)

KeyError: 'innopolis_temperature'